services:
  - type: web
    name: harvion-gpt-backend
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: AI_API_URL
        sync: false
      - key: AI_SYSTEM_PROMPT
        sync: false
      - key: BYTEZ_KEY
        sync: false
